version: "3.7"

networks:
  test-net:
    driver: bridge

services:
  postgres-app:
    image: postgres:latest
    networks:
      - test-net
    restart: always
    container_name: postgres-app
    expose:
      - 5438
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
                - ./postgres-data:/var/lib/postgresql/data
                - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
